[package]
name = "setup1-shared"
version = "0.1.0"
authors = ["The Aleo Team <hello@aleo.org>"]
edition = "2018"

[features]
default = []
async_message = ["tokio"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.7", features = ["io-util"], optional = true }
